version: '3.5'
services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        UID: ${UID}
      target: base
    restart: always
    ports:
      - ${NGINX_HTTP_PORT}:80
    depends_on:
      - php-fpm
    healthcheck:
      test: curl -f http://localhost/healthcheck
      timeout: 5s
  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        UID: ${UID}
      target: fpm
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
    healthcheck:
      test: cgi-fcgi -bind -connect 127.0.0.1:9000
      timeout: 5s
  redis:
    image: bitnami/redis:latest
    restart: always
    volumes:
      - redis:/bitnami/redis/data
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    healthcheck:
      test: redis-cli -a ${REDIS_PASSWORD} PING
      timeout: 3s
  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - 18025:8025

volumes:
  redis:
